#!/usr/bin/env python3
"""
Simple Flask app to check Telegram IDs
"""

from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        phone = request.form.get('phone')
        return f"You entered: {phone}"
    
    return """
<form method=post>
<label>Phone Number:<br><input name=phone></label>
<button type=submit>Check</button>
</form>
"""

if __name__ == '__main__':
    app.run(port=5000)
